return { mytest = function() print('my test called') error() end }
